name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  json-check:
    name: Check if JSON is valid by Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validating
        uses: lyubick/action-YAML-schema-validator@v2.1
        with:
          json-schema-file: .vscode/opensource.schema.json
          yaml-json-file-dir: base/index.json,extra/index.json